### ISSUE TITLE
Exit zrok

### ISSUE THREAD

**Issue by testman42** [forslund/white-house-adventure#1]
Am I missing something or is there no way to stop playing zork once you start it?

**Comment by forslund** [comment]
Quit or exit should work

Den 24 okt. 2017 2:15 em skrev "Testman" <notifications@github.com>:

**Comment by forslund** [comment]
@testman42 do you still have problems exiting Zork?

Should the vocabulary be updated in some way?

**Comment by testman42** [comment]
nope, exit worked fine last time I checked.

**Comment by forslund** [comment]
Ok closing this now.
